login:
    pattern:   /login
    defaults:  { _controller: TennisBookUserBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: TennisBookUserBundle:Security:loginCheck }

tennis_book_user:
    resource: "@TennisBookUserBundle/Resources/config/routing.yml"
    prefix:   /

tennis_book_accueil:
    resource: "@TennisBookAccueilBundle/Resources/config/routing.yml"
    prefix:   /



