security:
   encoders:
            TennisBook\UserBundle\Entity\User: sha512

   role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

   firewalls:
      main:
          pattern: ^/
          logout:       true
          anonymous:    true
          form_login:
              login_path:  /login
              check_path:  /login_check

   providers:
        main:
            entity: { class: TennisBook\UserBundle\Entity\User, property: username }

   access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }