<?php

namespace TennisBook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    public function getRecentAnnonces () {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM TennisBookCoreBundle:Annonce p ORDER BY p.date DESC ')
            ->setMaxResults(10)
            ->getResult();
    }
}
